/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_go_trove_util_Deflater */

#ifndef _Included_com_go_trove_util_Deflater
#define _Included_com_go_trove_util_Deflater
#ifdef __cplusplus
extern "C" {
#endif
#undef com_go_trove_util_Deflater_DEFLATED
#define com_go_trove_util_Deflater_DEFLATED 8L
#undef com_go_trove_util_Deflater_NO_COMPRESSION
#define com_go_trove_util_Deflater_NO_COMPRESSION 0L
#undef com_go_trove_util_Deflater_BEST_SPEED
#define com_go_trove_util_Deflater_BEST_SPEED 1L
#undef com_go_trove_util_Deflater_BEST_COMPRESSION
#define com_go_trove_util_Deflater_BEST_COMPRESSION 9L
#undef com_go_trove_util_Deflater_DEFAULT_COMPRESSION
#define com_go_trove_util_Deflater_DEFAULT_COMPRESSION -1L
#undef com_go_trove_util_Deflater_FILTERED
#define com_go_trove_util_Deflater_FILTERED 1L
#undef com_go_trove_util_Deflater_HUFFMAN_ONLY
#define com_go_trove_util_Deflater_HUFFMAN_ONLY 2L
#undef com_go_trove_util_Deflater_DEFAULT_STRATEGY
#define com_go_trove_util_Deflater_DEFAULT_STRATEGY 0L
#undef com_go_trove_util_Deflater_NO_FLUSH
#define com_go_trove_util_Deflater_NO_FLUSH 0L
#undef com_go_trove_util_Deflater_SYNC_FLUSH
#define com_go_trove_util_Deflater_SYNC_FLUSH 2L
#undef com_go_trove_util_Deflater_FULL_FLUSH
#define com_go_trove_util_Deflater_FULL_FLUSH 3L
#undef com_go_trove_util_Deflater_FINISH
#define com_go_trove_util_Deflater_FINISH 4L
/*
 * Class:     com_go_trove_util_Deflater
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_go_trove_util_Deflater_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     com_go_trove_util_Deflater
 * Method:    init
 * Signature: (IIZ)J
 */
JNIEXPORT jlong JNICALL Java_com_go_trove_util_Deflater_init
  (JNIEnv *, jobject, jint, jint, jboolean);

/*
 * Class:     com_go_trove_util_Deflater
 * Method:    setDictionary
 * Signature: (J[BII)V
 */
JNIEXPORT void JNICALL Java_com_go_trove_util_Deflater_setDictionary
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_go_trove_util_Deflater
 * Method:    deflate
 * Signature: (JIZ[BII[BII)I
 */
JNIEXPORT jint JNICALL Java_com_go_trove_util_Deflater_deflate
  (JNIEnv *, jobject, jlong, jint, jboolean, jbyteArray, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     com_go_trove_util_Deflater
 * Method:    getAdler
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_go_trove_util_Deflater_getAdler
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_go_trove_util_Deflater
 * Method:    getTotalIn
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_go_trove_util_Deflater_getTotalIn
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_go_trove_util_Deflater
 * Method:    getTotalOut
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_go_trove_util_Deflater_getTotalOut
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_go_trove_util_Deflater
 * Method:    reset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_go_trove_util_Deflater_reset
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_go_trove_util_Deflater
 * Method:    end
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_go_trove_util_Deflater_end
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
