/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_go_trove_file_MappedFileBuffer */

#ifndef _Included_com_go_trove_file_MappedFileBuffer
#define _Included_com_go_trove_file_MappedFileBuffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_go_trove_file_MappedFileBuffer
 * Method:    open
 * Signature: (JIJI)J
 */
JNIEXPORT jlong JNICALL Java_com_go_trove_file_MappedFileBuffer_open
  (JNIEnv *, jclass, jlong, jint, jlong, jint);

/*
 * Class:     com_go_trove_file_MappedFileBuffer
 * Method:    read
 * Signature: ([BIIJ)I
 */
JNIEXPORT jint JNICALL Java_com_go_trove_file_MappedFileBuffer_read
  (JNIEnv *, jobject, jbyteArray, jint, jint, jlong);

/*
 * Class:     com_go_trove_file_MappedFileBuffer
 * Method:    write
 * Signature: ([BIIJ)I
 */
JNIEXPORT jint JNICALL Java_com_go_trove_file_MappedFileBuffer_write
  (JNIEnv *, jobject, jbyteArray, jint, jint, jlong);

/*
 * Class:     com_go_trove_file_MappedFileBuffer
 * Method:    read0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_go_trove_file_MappedFileBuffer_read0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_go_trove_file_MappedFileBuffer
 * Method:    write0
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_go_trove_file_MappedFileBuffer_write0
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_go_trove_file_MappedFileBuffer
 * Method:    force
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_go_trove_file_MappedFileBuffer_force
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
